# Generated by Django 4.0.2 on 2022-04-10 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=10, null=True)),
                ('class_section', models.CharField(blank=True, max_length=4000, null=True)),
                ('class_number', models.CharField(blank=True, max_length=20, null=True)),
                ('class_title', models.CharField(blank=True, max_length=20, null=True)),
                ('class_topic_formal_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor', models.CharField(blank=True, max_length=50, null=True)),
                ('enrollment_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_days', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_time_start', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_time_end', models.CharField(blank=True, max_length=50, null=True)),
                ('term', models.CharField(blank=True, max_length=50, null=True)),
                ('term_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
            ],
        ),
    ]
