# Generated by Django 4.0.2 on 2022-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='profiles.Courses'),
        ),
    ]
