# Generated by Django 4.0.2 on 2022-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=250)),
                ('prof', models.CharField(max_length=250)),
                ('classTime', models.DateTimeField()),
            ],
        ),
    ]
