# Generated by Django 4.0.2 on 2022-04-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybud', '0001_initial'),
        ('profiles', '0002_test_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sessions',
            field=models.ManyToManyField(to='studybud.Session'),
        ),
    ]
