# Generated by Django 4.0.1 on 2022-04-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_username_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
    ]
