# Generated by Django 4.0.2 on 2022-04-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_test_remove_profile_id_alter_profile_user'),
        ('profiles', '0003_delete_classes_profile_id'),
    ]

    operations = [
    ]
