# Generated by Django 4.0.1 on 2022-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
