# Generated by Django 4.0.2 on 2022-04-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_20220410_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('catelog_number', models.CharField(blank=True, max_length=10, null=True)),
                ('class_section', models.CharField(blank=True, max_length=4000, null=True)),
                ('class_number', models.CharField(blank=True, max_length=20, null=True)),
                ('class_title', models.SlugField(default='test')),
                ('class_topic_formal_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor', models.CharField(blank=True, max_length=50, null=True)),
                ('enrollment_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_days', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_time_start', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_time_end', models.CharField(blank=True, max_length=50, null=True)),
                ('term', models.CharField(blank=True, max_length=50, null=True)),
                ('term_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
