# Generated by Django 4.0.2 on 2022-03-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and time of session')),
                ('attendees', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=9)),
            ],
        ),
    ]
