# Generated by Django 4.0.2 on 2022-03-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               # ('attendees', models.IntegerField(default=1)),
                ('date', models.DateTimeField(verbose_name='meeting date')),
                ('location', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=9)),
                ('details', models.TextField(max_length=250)),
            ],
        ),
    ]
