# Generated by Django 4.0.2 on 2022-04-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='host',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
