# Generated by Django 4.0.2 on 2022-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_course_profile_courses'),
        ('studybud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='course',
        ),
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ManyToManyField(to='profiles.Course'),
        ),
    ]
