# Generated by Django 4.0.2 on 2022-04-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_course_profile_courses'),
        ('studybud', '0002_remove_session_course_session_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='course',
        ),
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.course'),
            preserve_default=False,
        ),
    ]
