# Generated by Django 4.0.2 on 2022-04-14 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studybud', '0003_alter_session_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='attendees',
        ),
        migrations.AddField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(related_name='users_attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
