name: GitHub Actions Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up
      uses: actions/setup-python@v2
      with:
      python-version: 3.9
    - name: Run tests
    - working-directory: ../../
    - run: python manage.py test
#source: https://docs.github.com/en/actions/quickstart