name: GitHub Actions Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: 
        python-version: 3.9
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python manage.py test

    
#source: https://docs.github.com/en/actions/quickstart
