name: GitHub Actions Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: python manage.py test
#source: https://docs.github.com/en/actions/quickstart